[package]
name = "rusty-place"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
warp = "0.3.2"
mtpng = "0.3.5"